<a href="https://colab.research.google.com/github/JulianaAiolfi/Estudando_Analise_de_dados-Python/blob/main/Notebook_Aulas/Aula03_23_03_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Arrays


In [4]:
teste= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#                  0         1      2        3

teste1 = [1,2,3] #criando lista

In [5]:
print(teste)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
teste[1]

array([4, 5, 6])

In [7]:
muntidimensao = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [8]:
muntidimensao

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
lista_alunos = np.array([[["Luis",27],["Wagner", 30],["Juliana", 33]],[["Pedro",25],["Valter", 35],["Nathalia", 25]]])
#                                     0                                                 1
#                              0          1                 2                0            1                  2
#                            0    1      0       1        0      1        0      1       0      1         0     1
#
print(lista_alunos)

[[['Luis' '27']
  ['Wagner' '30']
  ['Juliana' '33']]

 [['Pedro' '25']
  ['Valter' '35']
  ['Nathalia' '25']]]


In [10]:
lista_alunos[1][1][1] = 36


In [11]:
lista_alunos

array([[['Luis', '27'],
        ['Wagner', '30'],
        ['Juliana', '33']],

       [['Pedro', '25'],
        ['Valter', '36'],
        ['Nathalia', '25']]], dtype='<U21')

In [12]:
lista_alunos.shape

(2, 3, 2)

In [13]:
len(lista_alunos)

2

In [14]:
lista_alunos.ndim

3

In [15]:
lista_alunos.size

12

Pandas


In [16]:
import pandas as pd

In [17]:
idades = pd.Series([12,13,34,56,78,99,54])

In [18]:
idades

0    12
1    13
2    34
3    56
4    78
5    99
6    54
dtype: int64

In [19]:
idades_2 = pd.Series([27,13,34,56], index = ["Luis","Ze","Valter","João"])

In [20]:
idades_2

Luis      27
Ze        13
Valter    34
João      56
dtype: int64

In [21]:
idades_2.values

array([27, 13, 34, 56])

In [22]:
idades_2.index

Index(['Luis', 'Ze', 'Valter', 'João'], dtype='object')

DataFrame ou Dataset

In [23]:
df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]), columns=['a','b','c'], index=['Luis','Valter','Wagner'])

In [24]:
df

a  b  c
Luis    1  2  3
Valter  4  5  6
Wagner  7  8  9

In [25]:
dados = {'a':[1,4,7], 'b':[2,5,8], 'c':[3,6,9]}
df2 = pd.DataFrame(data= dados, index=['Luis','Valter','Wagner'])
print(dados)
print(df2)

{'a': [1, 4, 7], 'b': [2, 5, 8], 'c': [3, 6, 9]}
        a  b  c
Luis    1  2  3
Valter  4  5  6
Wagner  7  8  9


In [26]:
df = pd.read_excel("bank-full.xlsx", sheet_name = "Sheet 1 - bank-full")
#df = pd.read_excel("C:\\Users\\luis.corrente\\Soluções em Dados\\Solucoes em Dados - Documentos\\Clientes\\Impacta\\Aulas\\Python\\Arquivos\\bank-full.xlsx")
#df = pd.read_csv("bank-full.xlsx")


In [27]:
#mostra o cabeçalho do dataframe
df.head(10)

age           job   marital  education default  balance housing loan  \
0   58    management   married   tertiary      no     2143     yes   no   
1   44    technician    single  secondary      no       29     yes   no   
2   33  entrepreneur   married  secondary      no        2     yes  yes   
3   47   blue-collar   married    unknown      no     1506     yes   no   
4   33       unknown    single    unknown      no        1      no   no   
5   35    management   married   tertiary      no      231     yes   no   
6   28    management    single   tertiary      no      447     yes  yes   
7   42  entrepreneur  divorced   tertiary     yes        2     yes   no   
8   58       retired   married    primary      no      121     yes   no   
9   43    technician    single  secondary      no      593     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome  \
0  unknown    5   may       261         1     -1         0  unknown   
1  unknown    5   may       151         1     -1         0  unknown   
2  unknown    5   may        76         1     -1         0  unknown   
3  unknown    5   may        92         1     -1         0  unknown   
4  unknown    5   may       198         1     -1         0  unknown   
5  unknown    5   may       139         1     -1         0  unknown   
6  unknown    5   may       217         1     -1         0  unknown   
7  unknown    5   may       380         1     -1         0  unknown   
8  unknown    5   may        50         1     -1         0  unknown   
9  unknown    5   may        55         1     -1         0  unknown   

  Unnamed: 16  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN  
8         NaN  
9         NaN

In [28]:
#mostra o cabeçalho do dataframe
df.tail(10)

age           job   marital  education default  balance housing loan  \
45201   53    management   married   tertiary      no      583      no   no   
45202   34        admin.    single  secondary      no      557      no   no   
45203   23       student    single   tertiary      no      113      no   no   
45204   73       retired   married  secondary      no     2850      no   no   
45205   25    technician    single  secondary      no      505      no  yes   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  \
45201   cellular   17   nov       226         1    184         4  success   
45202   cellular   17   nov       224         1     -1         0  unknown   
45203   cellular   17   nov       266         1     -1         0  unknown   
45204   cellular   17   nov       300         1     40         8  failure   
45205   cellular   17   nov       386         2     -1         0  unknown   
45206   cellular   17   nov       977         3     -1         0  unknown   
45207   cellular   17   nov       456         2     -1         0  unknown   
45208   cellular   17   nov      1127         5    184         3  success   
45209  telephone   17   nov       508         4     -1         0  unknown   
45210   cellular   17   nov       361         2    188        11    other   

      Unnamed: 16  
45201         NaN  
45202         NaN  
45203         NaN  
45204         NaN  
45205         NaN  
45206         NaN  
45207         NaN  
45208       False  
45209       False  
45210       False

In [29]:
df.columns= ['idade','trabalho','estado civil', 'educacao', 'default', 'balance', 'housing', 'emprestimo', 'contato', 'dia','mes', 'duracao','campanha','pdays','previous', 'poutcome','naoinformado']

In [30]:
df

idade      trabalho estado civil   educacao default  balance housing  \
0         58    management      married   tertiary      no     2143     yes   
1         44    technician       single  secondary      no       29     yes   
2         33  entrepreneur      married  secondary      no        2     yes   
3         47   blue-collar      married    unknown      no     1506     yes   
4         33       unknown       single    unknown      no        1      no   
...      ...           ...          ...        ...     ...      ...     ...   
45206     51    technician      married   tertiary      no      825      no   
45207     71       retired     divorced    primary      no     1729      no   
45208     72       retired      married  secondary      no     5715      no   
45209     57   blue-collar      married  secondary      no      668      no   
45210     37  entrepreneur      married  secondary      no     2971      no   

      emprestimo    contato  dia  mes  duracao  campanha  pdays  previous  \
0             no    unknown    5  may      261         1     -1         0   
1             no    unknown    5  may      151         1     -1         0   
2            yes    unknown    5  may       76         1     -1         0   
3             no    unknown    5  may       92         1     -1         0   
4             no    unknown    5  may      198         1     -1         0   
...          ...        ...  ...  ...      ...       ...    ...       ...   
45206         no   cellular   17  nov      977         3     -1         0   
45207         no   cellular   17  nov      456         2     -1         0   
45208         no   cellular   17  nov     1127         5    184         3   
45209         no  telephone   17  nov      508         4     -1         0   
45210         no   cellular   17  nov      361         2    188        11   

      poutcome naoinformado  
0      unknown          NaN  
1      unknown          NaN  
2      unknown          NaN  
3      unknown          NaN  
4      unknown          NaN  
...        ...          ...  
45206  unknown          NaN  
45207  unknown          NaN  
45208  success        False  
45209  unknown        False  
45210    other        False  

[45211 rows x 17 columns]

In [31]:
#renomeia a coluna selecionada
df.rename(columns={'idade': "Idade", 'trabalho': "Profissao"}, inplace = True)

In [32]:
df.head()

Idade     Profissao estado civil   educacao default  balance housing  \
0     58    management      married   tertiary      no     2143     yes   
1     44    technician       single  secondary      no       29     yes   
2     33  entrepreneur      married  secondary      no        2     yes   
3     47   blue-collar      married    unknown      no     1506     yes   
4     33       unknown       single    unknown      no        1      no   

  emprestimo  contato  dia  mes  duracao  campanha  pdays  previous poutcome  \
0         no  unknown    5  may      261         1     -1         0  unknown   
1         no  unknown    5  may      151         1     -1         0  unknown   
2        yes  unknown    5  may       76         1     -1         0  unknown   
3         no  unknown    5  may       92         1     -1         0  unknown   
4         no  unknown    5  may      198         1     -1         0  unknown   

  naoinformado  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [33]:
#mostra a estrutura do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Idade         45211 non-null  int64 
 1   Profissao     45211 non-null  object
 2   estado civil  45211 non-null  object
 3   educacao      45211 non-null  object
 4   default       45211 non-null  object
 5   balance       45211 non-null  int64 
 6   housing       45211 non-null  object
 7   emprestimo    45211 non-null  object
 8   contato       45211 non-null  object
 9   dia           45211 non-null  int64 
 10  mes           45211 non-null  object
 11  duracao       45211 non-null  int64 
 12  campanha      45211 non-null  int64 
 13  pdays         45211 non-null  int64 
 14  previous      45211 non-null  int64 
 15  poutcome      45211 non-null  object
 16  naoinformado  3 non-null      object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [34]:
#estatistica baisca de colunas numéricas = int64
df.describe()

Idade        balance           dia       duracao      campanha  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [35]:
#estatistica baisca de colunas textos = object 
df.describe(include=['O'])

Profissao estado civil   educacao default housing emprestimo  \
count         45211        45211      45211   45211   45211      45211   
unique           12            3          4       2       2          2   
top     blue-collar      married  secondary      no     yes         no   
freq           9732        27214      23202   44396   25130      37967   

         contato    mes poutcome naoinformado  
count      45211  45211    45211            3  
unique         3     12        4            1  
top     cellular    may  unknown        False  
freq       29285  13766    36959            3

In [36]:
#estatistica baisca de colunas textos = object 
df.describe(include=['O']).T #transpode

count unique          top   freq
Profissao     45211     12  blue-collar   9732
estado civil  45211      3      married  27214
educacao      45211      4    secondary  23202
default       45211      2           no  44396
housing       45211      2          yes  25130
emprestimo    45211      2           no  37967
contato       45211      3     cellular  29285
mes           45211     12          may  13766
poutcome      45211      4      unknown  36959
naoinformado      3      1        False      3

In [37]:
df.describe(include='all')

Idade    Profissao estado civil   educacao default  \
count   45211.000000        45211        45211      45211   45211   
unique           NaN           12            3          4       2   
top              NaN  blue-collar      married  secondary      no   
freq             NaN         9732        27214      23202   44396   
mean       40.936210          NaN          NaN        NaN     NaN   
std        10.618762          NaN          NaN        NaN     NaN   
min        18.000000          NaN          NaN        NaN     NaN   
25%        33.000000          NaN          NaN        NaN     NaN   
50%        39.000000          NaN          NaN        NaN     NaN   
75%        48.000000          NaN          NaN        NaN     NaN   
max        95.000000          NaN          NaN        NaN     NaN   

              balance housing emprestimo   contato           dia    mes  \
count    45211.000000   45211      45211     45211  45211.000000  45211   
unique            NaN       2          2         3           NaN     12   
top               NaN     yes         no  cellular           NaN    may   
freq              NaN   25130      37967     29285           NaN  13766   
mean      1362.272058     NaN        NaN       NaN     15.806419    NaN   
std       3044.765829     NaN        NaN       NaN      8.322476    NaN   
min      -8019.000000     NaN        NaN       NaN      1.000000    NaN   
25%         72.000000     NaN        NaN       NaN      8.000000    NaN   
50%        448.000000     NaN        NaN       NaN     16.000000    NaN   
75%       1428.000000     NaN        NaN       NaN     21.000000    NaN   
max     102127.000000     NaN        NaN       NaN     31.000000    NaN   

             duracao      campanha         pdays      previous poutcome  \
count   45211.000000  45211.000000  45211.000000  45211.000000    45211   
unique           NaN           NaN           NaN           NaN        4   
top              NaN           NaN           NaN           NaN  unknown   
freq             NaN           NaN           NaN           NaN    36959   
mean      258.163080      2.763841     40.197828      0.580323      NaN   
std       257.527812      3.098021    100.128746      2.303441      NaN   
min         0.000000      1.000000     -1.000000      0.000000      NaN   
25%       103.000000      1.000000     -1.000000      0.000000      NaN   
50%       180.000000      2.000000     -1.000000      0.000000      NaN   
75%       319.000000      3.000000     -1.000000      0.000000      NaN   
max      4918.000000     63.000000    871.000000    275.000000      NaN   

       naoinformado  
count             3  
unique            1  
top           False  
freq              3  
mean            NaN  
std             NaN  
min             NaN  
25%             NaN  
50%             NaN  
75%             NaN  
max             NaN

In [38]:
#mostra a quantidade de numero em branco na base
df.isna().sum()

Idade               0
Profissao           0
estado civil        0
educacao            0
default             0
balance             0
housing             0
emprestimo          0
contato             0
dia                 0
mes                 0
duracao             0
campanha            0
pdays               0
previous            0
poutcome            0
naoinformado    45208
dtype: int64

In [39]:
df[['Idade','Profissao']]

Idade     Profissao
0         58    management
1         44    technician
2         33  entrepreneur
3         47   blue-collar
4         33       unknown
...      ...           ...
45206     51    technician
45207     71       retired
45208     72       retired
45209     57   blue-collar
45210     37  entrepreneur

[45211 rows x 2 columns]

In [40]:
#iloc: seleção baseadas nas posições dos índices das linhas e colunas(inteiros)
#loc: seleção baseadas nos nomes das variáveis
df.iloc[0:5,0:6]


Idade     Profissao estado civil   educacao default  balance
0     58    management      married   tertiary      no     2143
1     44    technician       single  secondary      no       29
2     33  entrepreneur      married  secondary      no        2
3     47   blue-collar      married    unknown      no     1506
4     33       unknown       single    unknown      no        1

In [41]:
df.loc[0:5,["Idade","Profissao"]]

Idade     Profissao
0     58    management
1     44    technician
2     33  entrepreneur
3     47   blue-collar
4     33       unknown
5     35    management

In [42]:
df.loc[[0,20,500],["Idade","Profissao"]]

Idade    Profissao
0       58   management
20      28  blue-collar
500     46       admin.

In [43]:
df.loc[df.Idade > 55]
df[df.Idade > 55]
#df.loc[df.score_felicidade > 5]

Idade    Profissao estado civil   educacao default  balance housing  \
0         58   management      married   tertiary      no     2143     yes   
8         58      retired      married    primary      no      121     yes   
13        58   technician      married    unknown      no       71     yes   
14        57     services      married  secondary      no      162     yes   
17        57  blue-collar      married    primary      no       52     yes   
...      ...          ...          ...        ...     ...      ...     ...   
45195     68      retired      married  secondary      no     1146      no   
45204     73      retired      married  secondary      no     2850      no   
45207     71      retired     divorced    primary      no     1729      no   
45208     72      retired      married  secondary      no     5715      no   
45209     57  blue-collar      married  secondary      no      668      no   

      emprestimo    contato  dia  mes  duracao  campanha  pdays  previous  \
0             no    unknown    5  may      261         1     -1         0   
8             no    unknown    5  may       50         1     -1         0   
13            no    unknown    5  may       71         1     -1         0   
14            no    unknown    5  may      174         1     -1         0   
17            no    unknown    5  may       38         1     -1         0   
...          ...        ...  ...  ...      ...       ...    ...       ...   
45195         no   cellular   16  nov      212         1    187         6   
45204         no   cellular   17  nov      300         1     40         8   
45207         no   cellular   17  nov      456         2     -1         0   
45208         no   cellular   17  nov     1127         5    184         3   
45209         no  telephone   17  nov      508         4     -1         0   

      poutcome naoinformado  
0      unknown          NaN  
8      unknown          NaN  
13     unknown          NaN  
14     unknown          NaN  
17     unknown          NaN  
...        ...          ...  
45195  success          NaN  
45204  failure          NaN  
45207  unknown          NaN  
45208  success        False  
45209  unknown        False  

[4900 rows x 17 columns]

In [44]:
df["Idade"].describe()

count    45211.000000
mean        40.936210
std         10.618762
min         18.000000
25%         33.000000
50%         39.000000
75%         48.000000
max         95.000000
Name: Idade, dtype: float64

In [45]:
df.loc[(df.Idade > 55) & (df.educacao.str.startswith("secondary"))]

Idade    Profissao estado civil   educacao default  balance housing  \
14        57     services      married  secondary      no      162     yes   
30        57   technician      married  secondary      no      839      no   
32        60       admin.      married  secondary      no       39     yes   
33        59  blue-collar      married  secondary      no        0     yes   
35        57   technician     divorced  secondary      no       63     yes   
...      ...          ...          ...        ...     ...      ...     ...   
45184     63      retired      married  secondary      no     1495      no   
45195     68      retired      married  secondary      no     1146      no   
45204     73      retired      married  secondary      no     2850      no   
45208     72      retired      married  secondary      no     5715      no   
45209     57  blue-collar      married  secondary      no      668      no   

      emprestimo    contato  dia  mes  duracao  campanha  pdays  previous  \
14            no    unknown    5  may      174         1     -1         0   
30           yes    unknown    5  may      225         1     -1         0   
32           yes    unknown    5  may      208         1     -1         0   
33            no    unknown    5  may      226         1     -1         0   
35            no    unknown    5  may      242         1     -1         0   
...          ...        ...  ...  ...      ...       ...    ...       ...   
45184         no   cellular   16  nov      138         1     22         5   
45195         no   cellular   16  nov      212         1    187         6   
45204         no   cellular   17  nov      300         1     40         8   
45208         no   cellular   17  nov     1127         5    184         3   
45209         no  telephone   17  nov      508         4     -1         0   

      poutcome naoinformado  
14     unknown          NaN  
30     unknown          NaN  
32     unknown          NaN  
33     unknown          NaN  
35     unknown          NaN  
...        ...          ...  
45184  success          NaN  
45195  success          NaN  
45204  failure          NaN  
45208  success        False  
45209  unknown        False  

[2028 rows x 17 columns]